### ISSUE TITLE
data.getEvidenceKeyFilter is returning True for all inputs

### ISSUE THREAD

**Issue by kirstin51D** [51Degrees/device-detection-java#46] opened 2023-07-21 08:50 UTC
A customer has identified a bug in the following code.

The line `data.getEvidenceKeyFilter().include(headerName))` is returning True for all inputs.

```
  MultiMap headers = request.headers();
  String userAgent = headers.get("user-agent");
  try(FlowData data = pipeline.createFlowData()) {
    for (Map.Entry<String, String> header : headers) {
      String headerName = header.getKey();
      if (data.getEvidenceKeyFilter().include(headerName)) {
        data.addEvidence("header." + headerName, header.getValue());
```

**Comment by Sara51D** [comment] 2023-07-27 11:27
We have looked further into this and can confirm that result returned by the shared usage element is working by design. We need to be able to receive all evidence provided through shared usage for us to then be able to decide what headers are relevant. Therefore we will close this issue as it is a non-issue.

**Closed by Sara51D** 2023-07-27 11:27 UTC
