### ISSUE TITLE
Memory leak while using library version 4.2

### ISSUE THREAD

**Issue by annawang** [51Degrees/device-detection-java#7] opened 2021-08-17 04:10 UTC
Hello, 
This is Anna from Sharethrough. We are using your device parse 4.2 in our Scala code. Although we close the flowData, we still see memory leak in our system. Could u please give us some suggestion? 

These are 2 approaches that we tried:
---------------------------first one----------------- 
val flowData = pipeline.createFlowData()
val result = Try {
          flowData.addEvidence("header.user-agent", uaStrWithoutForcedToFillString).process()
         ..............
}
flowData.close()

---------------------------second one---------------------
UserAgentParser.withResources(pipeline.createFlowData()) { pipeline =>
            pipeline.addEvidence("header.user-agent", uaStrWithoutForcedToFillString).process()
  ..................
}
def withResources[T <: AutoCloseable, V](resource: => T)(f: T => V): V = {
    require(resource != null, "resource is null")
    @SuppressWarnings(Array("org.wartremover.warts.Var", "org.wartremover.warts.Null"))
    var exception: Throwable = null
    try {
      f(resource)
    } catch {
      case NonFatal(e) =>
        exception = e
        throw e
    } finally {
      closeAndAddSuppressed(exception, resource)
    }
  }

  private def closeAndAddSuppressed(e: Throwable, resource: AutoCloseable): Unit = {
    if (e != null) {
      try {
        resource.close()
      } catch {
        case NonFatal(suppressed) =>
          e.addSuppressed(suppressed)
      }
    } else {
      resource.close()
    }
  }
----------------------------------------------------------------------------

**Comment by Joseph51D** [comment] 2021-08-18 16:30
Hi @annawang 

Can you provide me with the exact version of the device detection library you are referencing and can you provide me with your device detection + pipeline builder options?

It would also be good to know what are the machine specs you're running this on and your JVM configuration, specifically arguments related to GC.

Thanks,
Joe

**Comment by gilreathjw** [comment] 2021-08-20 16:43
Hi @Joseph51D , Here's some more info for you:

- device detection library version in question is 4.2.0
- device detection + pipeline builder options for our most recent iteration can be found below; Note, even with the implementation below, our tests regularly displayed the following warning:

[WARN ] f.p.c.f.Pipeline - Pipeline '371156515' finalised. It is recommended that instance lifetimes are managed explicitly with a 'try' block or calling the close method as part of a 'finally' block.


```
import fiftyone.devicedetection.hash.engine.onpremise.flowelements.DeviceDetectionHashEngine;
import fiftyone.devicedetection.hash.engine.onpremise.flowelements.DeviceDetectionHashEngineBuilder;
import fiftyone.devicedetection.shared.DeviceData;
import fiftyone.pipeline.core.data.FlowData;
import fiftyone.pipeline.core.flowelements.PipelineBuilder;
import fiftyone.pipeline.engines.Constants;
import fiftyone.pipeline.engines.data.AspectPropertyValue;

import java.util.Optional;
import java.util.function.Function;

public class UserAgentPipelineHelper {
    public static final String UNKNOWN = "unknown";

    public static UserAgentParsedData parseUserAgentData(String dataFilePath, String userAgentEvidence) {
        try (FlowData data = createFlowData(dataFilePath)) {
            data.addEvidence("header.user-agent", userAgentEvidence).process();

            DeviceData device = data.get(DeviceData.class);
            String os = getPropertyOrUnknown(device, DeviceData::getPlatformName);
            String browser = getPropertyOrUnknown(device, DeviceData::getBrowserName);
            String version = browser.equals(UNKNOWN) ? UNKNOWN : getPropertyOrUnknown(device, DeviceData::getBrowserVersion);
            String hardwareMake = getPropertyOrUnknown(device, DeviceData::getHardwareVendor);
            String hardwareModel = getPropertyOrUnknown(device, DeviceData::getHardwareModel);
            Optional<String> deviceType = getProperty(device, DeviceData::getDeviceType);
            // data.close(); // adding this here did nothing to fix the memory leak
            return new UserAgentParsedData(os, browser, version, hardwareMake, hardwareModel, deviceType);
        } catch (Exception e) {
            return new UserAgentParsedData(UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, Optional.of(UNKNOWN));
        }
    }

    private static String getPropertyOrUnknown(DeviceData deviceData, Function<DeviceData, AspectPropertyValue<String>> fn) {
        try {
            return fn.apply(deviceData).getValue();
        } catch (Exception ignored) {
            return UNKNOWN;
        }
    }

    private static Optional<String> getProperty(DeviceData deviceData, Function<DeviceData, AspectPropertyValue<String>> fn) {
        try {
            return Optional.of(fn.apply(deviceData).getValue());
        } catch (Exception ignored) {
            return Optional.empty();
        }
    }

    private static FlowData createFlowData(String dataFilePath) throws Exception {
        final DeviceDetectionHashEngine engine = new DeviceDetectionHashEngineBuilder()
                .setPerformanceProfile(Constants.PerformanceProfiles.MaxPerformance)
                .setAutoUpdate(false)
                .setDataUpdateOnStartup(false)
                .setUpdateMatchedUserAgent(true)
                .build(dataFilePath, false);

        return new PipelineBuilder()
                .addFlowElement(engine)
                .build()
                .createFlowData();
    }
}
```

- machine specs, cloud

we use these AWS instance types via spot.io:
```
  "c5.2xlarge",
  "c5.4xlarge", 
  "c5.12xlarge",
  "c5n.2xlarge", 
  "c5n.4xlarge",
  "c5d.2xlarge",
  "c5d.4xlarge",
  "c5d.12xlarge",
  "c5a.2xlarge",
  "c5a.4xlarge",
  "c5a.8xlarge",
  "c5a.12xlarge",
  "c5a.16xlarge"
```

- machine specs, local

MacBook Pro (15-inch, 2018) MacOS Big Sur version 11.4
Processor: 2.2 GHz 6-Core Intel Core i7
Memory: 32 GB 2400 MHz DDR4

- JVM configuration

we add these options via a bash script, in either case:

```
|addJava "-Davailability_zone=$EC2_ZONE"
|addJava "-Dinstance_id=$EC2_ID"
|addJava "-Dconfig.resource=$ADSERVER_ENVIRONMENT.conf"
|addJava "-Dcom.sun.management.jmxremote.port=$REMOTE_PORT"
|addJava "-Dcom.sun.management.jmxremote.rmi.port=$RMI_PORT"
|addJava "-Dcom.sun.management.jmxremote.ssl=false"
|addJava "-Dcom.sun.management.jmxremote.authenticate=false"
|addJava "-Xms$MIN_HEAP"
|addJava "-Xmx$MAX_HEAP"
|addJava "-XX:+UseG1GC"
|addJava "-XX:MaxTenuringThreshold=15"
|addJava "-XX:MaxMetaspaceSize=200M"
|addJava "-XX:MaxGCPauseMillis=100"
|addJava "-XX:+UseStringDeduplication"
|addJava "-XX:+DisableExplicitGC"
|addJava "-XX:+HeapDumpOnOutOfMemoryError"
|addJava "-XX:-OmitStackTraceInFastThrow"
```

**Comment by Joseph51D** [comment] 2021-08-23 15:44
Hi @gilreathjw 

Thanks for the additional info.

What's happening here is a new instance of `Pipeline` and `DeviceDetectionHashEngine` is being created every time the `createFlowData(dataFilePath)` method is called. 

With your current performance configuration (MaxPerformance), the data file is loaded into memory on start-up. The creation of the `DeviceDetectionHashEngine` is quite intensive so we recommend you create just one instance which will last the lifetime of the application. Using singletons is one way of doing this. The same goes for the Pipeline.

Additionally, while you have used the `try` statement to call the `createFlowData` method, the dispose method on the `FlowData` object returned does not dispose the of the Pipeline as this is also intended to be created once and used multiple times. That is also why you are seeing the warning `Pipeline '371156515' finalised. ...` as the reference is lost after the call to `createFlowData(dataFilePath)` and so the Pipeline is finalised by the garbage collector. 

I've taken the liberty of modifying your sample code and I've also written an example Main class which I've used to test it:

**UserAgentPipelineHelper.java**:
```java
public class UserAgentPipelineHelper {
    public static final String UNKNOWN = "unknown";

    public static UserAgentParsedData parseUserAgentData(Pipeline pipeline, String userAgentEvidence) {
        try (FlowData data = pipeline.createFlowData()) {
            data.addEvidence("header.user-agent", userAgentEvidence).process();

            DeviceData device = data.get(DeviceData.class);
            String os = getPropertyOrUnknown(device, DeviceData::getPlatformName);
            String browser = getPropertyOrUnknown(device, DeviceData::getBrowserName);
            String version = browser.equals(UNKNOWN) ? UNKNOWN : getPropertyOrUnknown(device, DeviceData::getBrowserVersion);
            String hardwareMake = getPropertyOrUnknown(device, DeviceData::getHardwareVendor);
            String hardwareModel = getPropertyOrUnknown(device, DeviceData::getHardwareModel);
            Optional<String> deviceType = getProperty(device, DeviceData::getDeviceType);

            return new UserAgentParsedData(os, browser, version, hardwareMake, hardwareModel, deviceType);
        } catch (Exception e) {
            return new UserAgentParsedData(UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, Optional.of(UNKNOWN));
        }
    }

    private static String getPropertyOrUnknown(DeviceData deviceData, Function<DeviceData, AspectPropertyValue<String>> fn) {
        try {
            return fn.apply(deviceData).getValue();
        } catch (Exception ignored) {
            return UNKNOWN;
        }
    }

    private static Optional<String> getProperty(DeviceData deviceData, Function<DeviceData, AspectPropertyValue<String>> fn) {
        try {
            return Optional.of(fn.apply(deviceData).getValue());
        } catch (Exception ignored) {
            return Optional.empty();
        }
    }
}
```

**Main.java** - example usage.
```java
public class Main {
    
    private static DeviceDetectionHashEngine engine;
    private static Pipeline pipeline ;
    
    public static void main(String[] args) throws Exception {
        
        // Create single instance of DeviceDetectionHashEngine.
        engine = new DeviceDetectionHashEngineBuilder()
            .setPerformanceProfile(Constants.PerformanceProfiles.MaxPerformance)
            .setAutoUpdate(false)
            .setDataUpdateOnStartup(false)
            .setUpdateMatchedUserAgent(true)
            .build("path/to/data/file", false);

        // Create single instance of Pipeline.
        pipeline = new PipelineBuilder()
            .addFlowElement(engine)
            .build();
        
        long i = 0;
        long start = System.nanoTime();
        // Loop forever.
        while (true) {
            long timeDiff = System.nanoTime() - start;
            i += 1;
            // Print loops per second.
            System.out.printf("%f - ", (float)i / (timeDiff / 1000000000));
            System.out.println(UserAgentPipelineHelper.parseUserAgentData(pipeline, "iPhone"));
        }
    }
}
```

Assuming this solution works for you, our next step is to make improvements to our documentation to provide clarity on the lifecycle of a Pipeline and Elements/Engines added to it. 

Thanks,
Joseph

**Comment by gilreathjw** [comment] 2021-08-23 21:12
Hi @Joseph51D , your explanation makes sense and is pretty clear, thank you. I'll have a look at implementing this soon and get back to you!

**Comment by annawang** [comment] 2021-08-25 02:00
Hello we are still seeing memory leak issue by following your instruction. 
![Screen Shot 2021-08-24 at 6 59 09 PM](https://user-images.githubusercontent.com/1061120/130713828-b916c43a-9aae-46a6-9a55-d078d99a3cff.png)

We also tried to only initiate pipeline once and do nothing else (comment out all the FlowData usage). Unfortunately, we see the same thing in the memory graph

**Comment by Joseph51D** [comment] 2021-08-25 14:34
Hi @annawang 

Thanks for the update. 

How does the memory leak manifest, are you receiving an OutOfMemoryError?

Can you run our [performance example](http://51degrees.com/device-detection-java/4.3/hash_2_performance_8java-example.html) in isolation and confirm that the memory leak still occurs?

I have run the performance example with a count of 100000000 iterations on 4 threads and can see no discernible memory leak.

![image](https://user-images.githubusercontent.com/25739804/130806971-2a98806f-bd9b-4efe-9848-0dbebd9f5090.png)

Thanks,
Joseph

**Comment by annawang** [comment] 2021-08-25 16:03
Hello, Yes, 
We did get OutOfMemoryError for our Docker containers. What we noticed is that, the container is probably ok for the first 4-5 hours and the memory usage will start to climb up, it will end up be almost 100%  and then we will see OutOfMemoryError which forces our Docker containers to be restarted.

If we removed that pipeline initialization in our code, that 18.2% of the native memory leak will disappear.  (see the attachment that I shared)

Context: we have the code there since this Feb. and that 18.2% memory leak were there since Feb. when we upgraded from 3.1 version to 4.2. We didn't pay too much attention because our traffic was low and it didn't have any performance issue. However, our traffic increases a lot recently and it triggered the OutOfMemoryError. Right now, we completely removed the library in order to avoid OutOfMemoryError. We can follow performance example that you shared but I am afraid that we can't catch anything just like we didn't catch this in the last 5-6 months.

**Comment by Joseph51D** [comment] 2021-08-28 11:51
Hi @annawang ,

This graph shows the process memory of our Performance Benchmark set to loop continuously over a period of about 18 hours.

![image](https://user-images.githubusercontent.com/25739804/131215477-0553c41b-8f05-4a69-84ad-142d876c9917.png)

We've also performed tests against our native library using the C Run-time Library to detect memory leaks and nothing was flagged up so we're confident that there isn't a memory leak in the code.

What memory constrains are you setting on the JVM (Xms/Xms)? It's worth mentioning that the device detection library loaded into memory is allocated off-heap so an additional ~150MB roughly equivalent to the size of the data file will be used.

Thanks,
Joe

**Comment by gilreathjw** [comment] 2021-08-30 13:28
Looking at our build.sbt it appears we use 10G for both min and max in production.

**Comment by Joseph51D** [comment] 2021-08-31 11:55
Thanks for the info, I'm going to run some tests in a Linux environment to see if the issue is platform related.

Can you run the performance example in your environment? The example is designed to simulate a high intensity work load, this will rule out any issues with the environment and perhaps point to an issue in the implementation. It could be that there is a usage scenario that we have not accounted for that is causing the issue.

I've attached a zip file containing a modified version of the Performance example, the modification simply allows the example to run for many more iterations before finishing. 

Inside the zip is a maven project which outputs a jar file. I've also attached a file containing User-Agents for your convenience but feel free to use your own.

run like:

```
java -jar .\Performance-1.0-SNAPSHOT-jar-with-dependencies.jar "path/to/datafile.hash" "path/to/1000000 UAs.csv"
```

[Performance.zip](https://github.com/51Degrees/device-detection-java/files/7083589/Performance.zip)
[1000000 UAs.zip](https://github.com/51Degrees/device-detection-java/files/7083595/1000000.UAs.zip)


Thanks,
Joe

**Comment by StephenDenham-districtm** [comment] 2021-08-31 16:33
Hi Joe, we were hoping you could provide a bit more around what you would like us to target in our test of the environment running the performance example. As @gilreathjw said, it's running on EC2 instances, with ECS in Docker containers, with those Java flags.
We could run it on a fresh EC2 instance with the same Java flags. We could also heavily edit our canary deployment to run the benchmark instead of own code but it would be more involved. Obviously if we know what we're trying to isolate I think we can ensure a cleaner test

**Comment by Joseph51D** [comment] 2021-09-01 14:38
Hi @StephenDenham-districtm 

We've performed further testing, this time using a Linux platform rather than the Windows platform and have confirmed that the native library is leaking a small number of bytes. Here's the dmalloc log output from running the PerfHash example in C

```
1630496533: 158: Dmalloc version '5.5.2' from 'http://dmalloc.com/'
1630496533: 158: flags = 0x403, logfile 'dmalloc.log'
1630496533: 158: interval = 0, addr = 0, seen # = 0, limit = 0
1630496533: 158: threads enabled, lock-on = 0, lock-init = 2
1630496533: 158: starting time = 1630496531
1630496533: 158: process pid = 13670
1630496533: 158:   error details: finding address in heap
1630496533: 158:   pointer '0x558a69b85010' from 'unknown' prev access 'unknown'
1630496533: 158: ERROR: free: cannot locate pointer in heap (err 22)
1630496533: 159:   error details: finding address in heap
1630496533: 159:   pointer '0x558a69b85050' from 'unknown' prev access 'unknown'
1630496533: 159: ERROR: free: cannot locate pointer in heap (err 22)
1630496534: 159: Dumping Chunk Statistics:
1630496534: 159: basic-block 4096 bytes, alignment 8 bytes
1630496534: 159: heap address range: 0x7f2e18aaf000 to 0x7f2e20d77000, 137134080 bytes
1630496534: 159:     user blocks: 29441 blocks, 120586182 bytes (99%)
1630496534: 159:    admin blocks: 15 blocks, 61440 bytes (0%)
1630496534: 159:    total blocks: 29456 blocks, 120651776 bytes
1630496534: 159: heap checked 0
1630496534: 159: alloc calls: malloc 78, calloc 6, realloc 0, free 75
1630496534: 159: alloc calls: recalloc 0, memalign 0, posix_memalign 0, valloc 0
1630496534: 159: alloc calls: new 0, delete 0
1630496534: 159:   current memory in use: 4806 bytes (11 pnts)
1630496534: 159:  total memory allocated: 120566867 bytes (84 pnts)
1630496534: 159:  max in use at one time: 120531019 bytes (64 pnts)
1630496534: 159: max alloced with 1 call: 120495937 bytes
1630496534: 159: max unused memory space: 28005 bytes (0%)
1630496534: 159: top 10 allocations:
1630496534: 159:  total-size  count in-use-size  count  source
1630496534: 159:           0      0           0      0  Total of 0
1630496534: 159: Dumping Not-Freed Pointers Changed Since Start:
1630496534: 159:  not freed: '0x7f2e20d36808|s1' (1182 bytes) from 'unknown'
1630496534: 159:  not freed: '0x7f2e20d5a608|s1' (272 bytes) from 'unknown'
1630496534: 159:  not freed: '0x7f2e20d5a808|s1' (272 bytes) from 'unknown'
1630496534: 159:  not freed: '0x7f2e20d5aa08|s1' (272 bytes) from 'unknown'
1630496534: 159:  not freed: '0x7f2e20d5ac08|s1' (360 bytes) from 'unknown'
1630496534: 159:  not freed: '0x7f2e20d5ae08|s1' (272 bytes) from 'unknown'
1630496534: 159:  not freed: '0x7f2e20d67d48|s1' (36 bytes) from 'unknown'
1630496534: 159:  not freed: '0x7f2e20d67d88|s1' (36 bytes) from 'unknown'
1630496534: 159:  not freed: '0x7f2e20d6ba88|s1' (56 bytes) from 'unknown'
1630496534: 159:  not freed: '0x7f2e20d76008|s1' (1024 bytes) from 'unknown'
1630496534: 159:  not freed: '0x7f2e20d76808|s1' (1024 bytes) from 'unknown'
1630496534: 159:  total-size  count  source
1630496534: 159:           0      0  Total of 0
1630496534: 159: ending time = 1630496534, elapsed since start = 0:00:03
```

We've addressed an oversight in our automatic memory checking and are currently working on resolving the issue. 

There's nothing further for you to do at the moment. I will post here once we have an update.

Thanks,
Joe

**Comment by tungntpham** [comment] 2021-09-02 14:21
Hi @StephenDenham-districtm,

After investigated further on Linux platform, we believe that the errors and the memory leaks warnings that we are seeing might be a false positive, resulted by using `dmalloc` in our test process.

I have raised this issue with `dmalloc` and is verifying with developer community. You can see the github issue [here](https://github.com/j256/dmalloc/issues/112) and the community discussion [here](https://stackoverflow.com/questions/69030958/dmalloc-output-not-freed-0x7f2e20d36808s1-1182-bytes-from-unknown-when).

In the mean time, we will be running number of other tests to investigate this issue further, including using `valgrind` on overnight test run.

We will update you with the further test results.

Many thanks for your patience,

Kind Regards.

**Comment by tungntpham** [comment] 2021-09-07 08:44
Hi @StephenDenham-districtm,

Many thanks for your patience. We have now run a number of tests on different platforms and have investigated the issues with dmalloc so we would like to update you on our findings.

Dmalloc issue update:
- We have got a reply from the dmalloc creator and we have compared the report from dmalloc with other utility such as jemalloc and we can confirm that the errors and memory leaks report that we are seeing on Linux platforms are not caused by our libraries but the implementation of the standard 'libc' libraries on Linux platforms.

Memory profiling update:
- We have run the same test on our Linux platform using the same flags (including GC1) and we don't see any significant increase in the memory usage over the course of 20hrs. Please see below images for more details
  - Jvm heap chart:
![LinuxG1GCJvm](https://user-images.githubusercontent.com/5407003/132312606-2bd1e717-54c4-44f6-af1f-a5fadf43e334.PNG)
  - Process heap chart:
![LinuxG1GCProc](https://user-images.githubusercontent.com/5407003/132312674-baaa4173-0976-4f9a-98c2-66152646513d.PNG)

- We have also tried to see if we might get different results on other Garbage Collection setting or other platforms but the results are fairly similar.
  - On Linux with default JDK 8 GC (Parallel garbage collector), the result is pretty steady with no significant increase:
    - Jvm heap chart:
![LinuxDefaultGCJvm](https://user-images.githubusercontent.com/5407003/132313160-8e361cda-8fd7-44ae-95dd-4c1ae3cd0eb0.PNG)
    - Process heap chart:
![LinuxDefaultGCProc](https://user-images.githubusercontent.com/5407003/132313222-9b815d10-a4dc-4adb-bfee-8ba2129241eb.PNG)

  - On MacOS Intel, with GC1 the result is also similar:
    - Jvm heap chart:
![MacIntel20hrsJvm](https://user-images.githubusercontent.com/5407003/132313351-658b5bde-ace2-4ea5-8728-d674fa91cb5b.PNG)
     - Process heap chart
![MacIntel20hrsProcMem](https://user-images.githubusercontent.com/5407003/132313383-4bab1014-1641-431a-ab3c-2fa1e863abc1.PNG)

So far with out testing we can't see any potential memory leaks with our libraries so at this point we would like to work with you on your test environment to get to the bottom of this issue. However, this requires dedicated resource from our team so I will discuss with our management team and they will contact you directly on the next step.

Kind Regards,

**Comment by StephenDenham-districtm** [comment] 2021-09-08 14:14
Thank you for the detailed investigation @tungntpham. We'll await your response regarding a dedicated resource for further analysis

**Comment by tungntpham** [comment] 2022-01-07 18:06
Hi @StephenDenham-districtm,

Since we are unable to reproduce the issue and our Customer Services team hasn't heard back from you on your decision to go ahead with the dedicated resource, we will proceed to close this issue for now.

Please feel free to re-open with further information.

Kind regards,
Tung.

**Closed by tungntpham** 2022-01-07 18:06 UTC
Labels: status: to be scheduled, status: awaiting external input
